name: ROBO SPANI

on:
  workflow_dispatch:

jobs:
  run-robo:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Rodar robo
        run: python main.py
